name: deploycoupon

on:
  push:
    branches: [master]  # Triggers on push to 'main' branch
  workflow_dispatch:
    inputs:
      branch:
        description: 'Deploy Coupon branch on Ubuntu server'
        required: true
        default: 'master'
        type: choice
        options:
          - master

permissions:
  contents: read
  actions: write

jobs:
  deploycoupon:
    runs-on: ubuntu-latest

    steps:

      # Step 1: SSH into the remote server and delete old files
      - name: SSH into server and delete old files and folders
        run: |
          ssh -i ${{ secrets.COUPON_SSH_KEY }} ubuntu@ec2-3-236-110-118.compute-1.amazonaws.com << 'EOF'
            echo "Deleting old files from /home/ubuntu/coupon..."
            rm -rf /home/ubuntu/coupon/*
            rm -rf /home/ubuntu/coupon.zip
            echo "Old files deleted"
            pwd
            ls -la /home/ubuntu
          EOF

      # Step 2: Clone the repository or pull the latest changes
      - name: Clone or Pull the latest code
        run: |
          ssh -i ${{ secrets.COUPON_SSH_KEY }} ubuntu@ec2-3-236-110-118.compute-1.amazonaws.com << 'EOF'
            if [ ! -d "/home/ubuntu/coupon" ]; then
              echo "Cloning the repository..."
              git clone https://github.com/tagglab/coupon.git /home/ubuntu/coupon
              echo "Cloning complete"
            else
              echo "Repository already exists. Pulling the latest changes..."
              cd /home/ubuntu/coupon
              git pull origin main
              echo "Git pull complete"
            fi
            pwd
            ls -la /home/ubuntu/coupon
          EOF

      # Step 3: Copy files into nginx server
      - name: Copy files into nginx server
        run: |
          ssh -i ${{ secrets.COUPON_SSH_KEY }} ubuntu@ec2-3-236-110-118.compute-1.amazonaws.com << 'EOF'
            echo "Copying files to Nginx server..."
            sudo rm -rf /var/www/html/coupon  # Remove old files from Nginx directory
            sudo cp -r /home/ubuntu/coupon /var/www/html/
            echo "Files copied to Nginx server"
            pwd
            ls -la /var/www/html
          EOF

      # Step 4: Restart nginx server
      - name: Restart nginx server
        run: |
          ssh -i ${{ secrets.COUPON_SSH_KEY }} ubuntu@ec2-3-236-110-118.compute-1.amazonaws.com << 'EOF'
            echo "Restarting nginx server..."
            sudo systemctl restart nginx
            echo "Nginx server restarted"
          EOF
