name: deploycoupon

on:
  push:
    branches: [main]
    paths:
      - '.github/workflows/**'
  workflow_dispatch:
    inputs:
      branch:
        description: 'Deploy Coupon branch on Ubuntu server'
        required: true
        default: 'main'
        type: choice
        options:
          - main

permissions:
  contents: read
  actions: write

jobs:
  deploycoupon:
    runs-on: ubuntu-latest

    steps:
      # Set up SSH using the PEM key only if not already set up
      - name: Set up SSH
        run: |
          if [ ! -f ~/.ssh/coupon.pem ]; then
            echo "Setting up SSH key..."
            echo "${{ secrets.COUPON_SSH_KEY }}" > ~/.ssh/coupon.pem
            chmod 600 ~/.ssh/coupon.pem
            ssh-keyscan -H ec2-3-236-110-118.compute-1.amazonaws.com >> ~/.ssh/known_hosts
            pwd
            ls -la
          else
            echo "SSH key already set up, skipping setup."
          fi

      # Delete old files and folders from logged-in Ubuntu server
      - name: Delete old files and folders from logged-in Ubuntu server
        run: |
          ssh -i ~/.ssh/coupon.pem ubuntu@ec2-3-236-110-118.compute-1.amazonaws.com << 'EOF'
            rm -rf /home/ubuntu/coupon
            rm -rf /home/ubuntu/coupon.zip
            pwd
            ls -la
            echo "Old files deleted"
          EOF

      # Checkout the code
      - name: Checkout code
        run: |
          if [ ! -d "/home/ubuntu" ]; then
            echo "Cloning the repository..."
            git clone https://github.com/tagglab/coupon.git /home/ubuntu/
            echo "Cloning complete"
          else
            echo "Repository already exists. Pulling the latest changes..."
            cd /home/ubuntu/coupon
            git pull origin main
            pwd
            ls -la
          fi

      # Delete previous files and folders from nginx server
      - name: Delete previous files and folders from nginx server
        run: |
          echo "Deleting previous files and folders..."
          sudo rm -rf /var/www/html/coupon
          sudo rm -rf /var/www/html/coupon.zip
          pwd
          ls -la

      # copy file or folder into nginx server `/var/www/html`
      - name: Copy file or folder into nginx server
        run: |
          if [ ! -d "/home/ubuntu/coupon" ]; then
            echo "Copying the files..."
            cp -r /home/ubuntu/coupon /var/www/html/
            pwd 
            ls -la
          else
            echo "Files already exist. Skipping copy."
            ls -la
          fi

      # Restart nginx server
      - name: Restart nginx server
        run: |
          echo "Restarting nginx server..."
          sudo systemctl restart nginx